# **Week 4 Homework**

---

### 1. **What does one need to do to use a module?**

* #### _In order to use a module, we first need to import the respective module, into our code-base by using the import statement_


### 2. **Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.**





In [1]:
# 2. The random module

import random

randomnumber = random.randrange(1,26)

print("\nRandom number is ...", randomnumber)




Random number is ... 16



### 3. **What is a benefit of using Exception handling?**

* #### _When an error is raised in the try block, the except block will be executed. Without the try block, the program will crash. With this code device we can keep going past many errors_


### 4. **NumPy arrays are like what Python data type?**

* #### _NumPy arrays are like Python lists_


### 5. **What is one of the main benefits of using NumPy arrays.**

* #### _Numpy arrays occupy less memory as compared to list_


### 6. **What is one of the main requirements about the 'dtype' of NumPy arrays?**

* #### _Needs to be the same or similar kind of data type_

### 7. **Of the 10 uses of NumPy, name 2.**

* #### _Searching, sorting, and counting_

* #### _Copying and viewing arrays_


### 8. **Name one of the other libraries we'll use with NumPy?**

* #### _Madpotlib_


### 9. **What is the shape of NumPy arrays?**

* #### _The shape is a tuple of non-negative integers that specify the dimentions, length and size of each array (3,2,4)_


### 10. **What is a Tensor?**

* #### _A tensor is an array with 3+ dimesions_


### 11. **Name a reason why it's better using NumPy for Data Analysis than using a Python List?**

* #### _NumPy arrays are fast compared to lists_


### 12. **When creating an "empty" array, where do the elements come from?**

* #### _The function empty creates an array whose intial content is random on the state of the memory_

In [7]:
# Use the DateTime module to get Current Date and Time, and save it to a variable. Then extract just the Full month name from that variable.

import datetime as dt


j = dt.datetime.now()

print("\nCurrent Date and Time is ...", j)

import datetime 

j = datetime.datetime.now()

print("\nJust the month is ...", j.strftime("%B"))


Current Date and Time is ... 2023-02-18 08:41:51.910369

Just the month is ... February


In [31]:
# Write a simple function that takes 2 parameters -- a first name and a day name.
#set a default value for the day name of Sunday.
#Have the function print out a greeting -- using the parameters -- that says something like "Hi first-name! Happy day-name!". Remember to use the variables in the greeting to replace first-name and day-name.
#Invoke this function with 2 variables.
#Invoke this function with 1 variable only.

def message(fname, dayname = "Sunday"):
  
    print("Hi", fname, "Happy", dayname, "!")

message("Jonathan", "Saturday") 
message("Jonathan")



Hi Jonathan Happy Saturday !
Hi Jonathan Happy Sunday !


In [32]:
#Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()


import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarray = array.reshape(2, 3, 2)

print(newarray)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [34]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

import numpy as np

j = np.linspace(0, 20, num = 6)
print("Array j is ...", j)

Array j is ... [ 0.  4.  8. 12. 16. 20.]


In [37]:
# Make a Deep Copy of the above array you created.

import copy

mArray = copy.deepcopy(j)


print("\nThe mArray ...\n", mArray)




The mArray ...
 [ 0.  4.  8. 12. 16. 20.]


### 13. **_What are 2 reasons we use NumPy arrays over Python Lists_**

#### * _We use NumPy arrays over Python lists because it is convenient to work with numpy and NumPy arrays occupy less memory as compared to list_

