# Week 5 Homework
---

### 1. What does Pandas stand for?

* #### _Pandas stands for Panel Data and references Python Data Analysis_


### 2. What are the 2 collections used in Pandas?

* #### _Pandas Series and Pandas DataFrames_


### 3. Name 4 things Pandas can do for us.

* #### _Pandas can load, manipulate, prepare, and analyze for us_


### 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

* #### _df.sort(values)_


### 5. What is a CSV

* #### _CSV stands for comma seperated files. CSV files contains plain text and is a well known format that can be read by everyone including pandas_


### 6. When cleaning data what values do we not like in our data?

* #### _Nulls_


In [65]:
# 1.Concatenate these 3 arrays into a new array named 'newArray'...
       # ([[25, 16]])
       # ([[11, 2], [13, 4]])
       # ([[7, 81], [5, 6], [11, 12]])

import numpy as np

arrayA = np.array([[25, 16]])
arrayB = np.array([[11, 2], [13, 4]])
arrayC = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC), axis = 0)

print("\nnewArray is ...\n", newArray)





# 2. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)

print("\nnewArray sorted is ...\n", sortedArray)

# 3.Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = np.reshape(sortedArray, (2, 2, 3))

print("\nreshapedArray is ...\n", reshapedArray)
# 4.Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

unpack = reshapedArray.reshape(4, 3)

name1, name2, name3, name4 = unpack

print("name1 = ", name1)
print("name2 = ", name2)
print("name3 = ", name3)
print("name4 = ", name4)


newArray is ...
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

newArray sorted is ...
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

reshapedArray is ...
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
name1 =  [16 25  2]
name2 =  [11  4 13]
name3 =  [ 7 81  5]
name4 =  [ 6 11 12]


In [24]:
# 5. Combined and sort the following arrays into one called 'comboArray' ...

    #one = ([10, 11, 12, 13, 14, 15, 16, 17])
    #two = ([20, 21, 22, 23, 24, 25, 26, 27])
    #three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis = 0)

comboArray = np.sort(comboArray)

print("\ncomboArray is ...", comboArray)


# 6.Take 'comboArray' and perform the following slicing activities:

#print sec1 - the 2nd element

sec1 = comboArray[2]

print("\nsec1 = \n", sec1)

#print sec2 - all elements from the 3rd element to the last
sec2 = comboArray[3:]
print("\nsec2 = \n", sec2)

#print sec3 - all elements from the 4th to the 14th elements
sec3 = comboArray[4:14]
print("\nsec3 = \n", sec3)

#print sec4 - the last 6 elements
sec4 = comboArray[-6:]
print("\nsec4 = \n", sec4)

#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
sec5 = comboArray[:-10]
print("\nsec5 = \n", sec5)

#print sec6 - from #20 every even element to the end
sec6 = comboArray[16::2]
print("\nsec6 = \n", sec6)

#print sec7 - from the last element moving forward, every 5th element.

sec7 = comboArray[-1::-5]
print("\nsec7 = \n", sec7)




comboArray is ... [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

sec1 = 
 2

sec2 = 
 [ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

sec3 = 
 [ 4  5  6  7 10 11 12 13 14 15]

sec4 = 
 [22 23 24 25 26 27]

sec5 = 
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]

sec6 = 
 [20 22 24 26]

sec7 = 
 [27 22 15 10  3]


In [31]:
# 7. Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --
    #([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        #[[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        #[[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

    #([[17.0, 70.0, 10.7]])

from numpy import array

arr1 = array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
     [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
     [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

arr2= array([[17.0, 70.0, 10.7]])

print("\naddition = \n", arr1 + arr2)

print("\nDivision =\n", arr1 / arr2)

print("\nMultiplication = \n", arr1 * arr2)


# 8.Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.
import numpy as np

arr3 = np.subtract(arr1, arr2)

print("\nSubraction = \n", arr3)

# 9. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.

divisible_by_3 = arr3[arr3 % 3 == 0]
print("\narr3 elements divided by 3 = \n", divisible_by_3)




addition = 
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

Division =
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]

Multiplication = 
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]

Subraction = 
 [[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]

arr3 elements divided by 3 = 
 [  3. -39.]


In [50]:
# 10.Using Series, create a DataFrame that looks like this:

#Ingredients	Quantity	Unit
#Flour	4	cups
#Milk	1	cup
#Eggs	2	large
#Spam	1	can
#Name: Dinner, dtype: object

import pandas as pd

ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name = "ingredients")

quantity = pd.Series(["4", "1", "2", "1"], name = "quantity")

unit = pd.Series(["Cups", "Cup","Large", "Can"], name = "unit")

dinner = pd.concat([ingredients, quantity, unit],  axis = 1)

print(dinner)


# 11. Take this data and create a DataFrame named studentData

studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }  
studentData = pd.DataFrame(studentData)


print("\nStudentData Dataframe:\n", studentData)

# 12. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData.insert(2, "deserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"])

print("\nstudentData with added column:\n", studentData)

# 13. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name', 'address'], inplace= True)

print("\nstudentData sorted by name first, then address\n", studentData)



  ingredients quantity   unit
0       Flour        4   Cups
1        Milk        1    Cup
2        Eggs        2  Large
3        Spam        1    Can

StudentData Dataframe:
       Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

studentData with added column:
       Name  Height       deserts Qualification  address  Age        Pets  \
0      Jai     5.1     ice cream           Msc    Delhi   21         Dog   
1  janusha     6.2  Cashew Fudge            MA     Doha   23       Bunny   
2   Gaurav     5.1       waffels           Msc  Chennai   24  Chinchilla   
3     Anuj     5.2  Carrot Halwa           Msc   Dakhar   21      Parrot   

            sport  
0           Dart

In [53]:
# 14. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df

df.to_csv('cows_and_goats.csv', index = False)



In [61]:
#15. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

vegetables = pd.DataFrame([["Onion", "Brocoli"], ["Shallot", "Cauliflower"]],
                           columns = ["Onion family", "Cabbage family"])
vegetables

vegetables.to_csv('vegetables.csv')

df = pd.read_csv("vegetables.csv")

print(df)
# (B)

vegetables = pd.DataFrame([["Onion", "Brocoli"], ["Shallot", "Cauliflower"]],
                           columns = ["Onion family", "Cabbage family"])

vegetables.to_csv('veggies.csv', index = False)

df = pd.read_csv('veggies.csv')

print(df)

   Unnamed: 0 Onion family Cabbage family
0           0        Onion        Brocoli
1           1      Shallot    Cauliflower
  Onion family Cabbage family
0        Onion        Brocoli
1      Shallot    Cauliflower
